# Generated by Django 5.0.2 on 2026-04-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Ubicación')),
                ('image', models.ImageField(blank=True, upload_to='events/', verbose_name='Imagen')),
                ('category', models.CharField(choices=[('culto', 'Culto'), ('especial', 'Evento Especial'), ('jovenes', 'Jóvenes'), ('ninos', 'Niños'), ('comunitario', 'Comunitario'), ('otro', 'Otro')], default='culto', max_length=20, verbose_name='Categoría')),
                ('registration_link', models.URLField(blank=True, verbose_name='Enlace de registro')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['date', 'time'],
            },
        ),
    ]
