# Generated by Django 5.0.2 on 2026-04-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('donor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del donante')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del donante')),
                ('payment_method', models.CharField(max_length=20, verbose_name='Método de pago')),
                ('transaction_id', models.CharField(blank=True, max_length=200, unique=True, verbose_name='ID de transacción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Transferencia Bancaria'), ('card', 'Tarjeta de Crédito/Débito'), ('other', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del banco')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de cuenta')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='Número de cuenta')),
                ('account_holder', models.CharField(blank=True, max_length=200, verbose_name='Titular')),
                ('identification', models.CharField(blank=True, max_length=50, verbose_name='Identificación')),
                ('paypal_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de PayPal')),
                ('card_image', models.ImageField(blank=True, upload_to='donations/', verbose_name='Imagen de tarjeta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opción de donación',
                'verbose_name_plural': 'Opciones de donación',
                'ordering': ['order'],
            },
        ),
    ]
