# Generated by Django 6.0.4 on 2026-04-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_sitesettings_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la iglesia'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='URL de Google Maps'),
        ),
    ]
