# Generated by Django 5.0.2 on 2026-04-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_sitesettings_email_sitesettings_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='schedule',
            field=models.TextField(blank=True, verbose_name='Horarios de cultos'),
        ),
    ]
