# Generated by Django 5.0.2 on 2026-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_sitesettings_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(blank=True, verbose_name='Sobre nosotros'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(blank=True, verbose_name='Misión'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Visión'),
        ),
    ]
