# Generated by Django 5.0.2 on 2026-04-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_sitesettings_about_us_sitesettings_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
    ]
