# Generated by Django 6.0.4 on 2026-04-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_sitesettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='donations_bible_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia (Donaciones)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donations_bible_verse',
            field=models.TextField(blank=True, verbose_name='Versículo (Donaciones)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donations_why_donate',
            field=models.TextField(blank=True, verbose_name='¿Por qué donar?'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faith_declaration',
            field=models.TextField(blank=True, verbose_name='Nuestra Declaración de Fe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_1_desc',
            field=models.TextField(blank=True, verbose_name='Pilar 1 (Descripción)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_1_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilar 1 (Título)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_2_desc',
            field=models.TextField(blank=True, verbose_name='Pilar 2 (Descripción)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_2_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilar 2 (Título)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_3_desc',
            field=models.TextField(blank=True, verbose_name='Pilar 3 (Descripción)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_3_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilar 3 (Título)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_4_desc',
            field=models.TextField(blank=True, verbose_name='Pilar 4 (Descripción)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_pillar_4_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilar 4 (Título)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_subtitle',
            field=models.TextField(blank=True, verbose_name='Subtítulo de Inicio'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título de Inicio'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='our_faith',
            field=models.TextField(blank=True, verbose_name='Nuestra Fe'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(blank=True, verbose_name='Sobre nosotros (Nuestra Historia)'),
        ),
    ]
