# Generated by Django 5.0.2 on 2026-04-26 03:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre de la alianza')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('logo', models.ImageField(blank=True, upload_to='alliances/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alianza',
                'verbose_name_plural': 'Alianzas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllianceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título del proyecto')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='alliance_projects/', verbose_name='Imagen')),
                ('impact_category', models.CharField(choices=[('educacion', 'Educación'), ('alimentacion', 'Alimentación'), ('vivienda', 'Vivienda'), ('salud', 'Salud'), ('deporte', 'Deporte y Recreación'), ('arte', 'Arte y Cultura'), ('ambiente', 'Medio Ambiente'), ('emprendimiento', 'Emprendimiento'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría de impacto')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Ubicación')),
                ('volunteers_needed', models.IntegerField(default=0, verbose_name='Voluntarios necesitados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='alliances.alliance', verbose_name='Alianza')),
            ],
            options={
                'verbose_name': 'Proyecto de alianza',
                'verbose_name_plural': 'Proyectos de alianzas',
                'ordering': ['-start_date'],
            },
        ),
    ]
