# Generated by Django 5.0.2 on 2026-04-26 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de galería',
                'verbose_name_plural': 'Categorías de galería',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagen')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.gallerycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['-created_at'],
            },
        ),
    ]
