# Generated by Django 5.0.2 on 2026-04-26 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='series/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('speaker', models.CharField(max_length=200, verbose_name='Predicador')),
                ('youtube_url', models.URLField(verbose_name='URL de YouTube')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('image', models.ImageField(blank=True, upload_to='sermons/', verbose_name='Imagen')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.series', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Predicación',
                'verbose_name_plural': 'Predicaciones',
                'ordering': ['-date'],
            },
        ),
    ]
